/*
 * WPCEM API
 * WPCEM API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SystemDeviceDTO;
import io.swagger.client.model.UserDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SystemUnitDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-06T16:15:45.073+02:00[Europe/Ljubljana]")public class SystemUnitDTO {

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("systemDevices")
  private List<SystemDeviceDTO> systemDevices = null;

  @SerializedName("users")
  private List<UserDTO> users = null;
  public SystemUnitDTO description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public SystemUnitDTO id(Long id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  public SystemUnitDTO name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public SystemUnitDTO systemDevices(List<SystemDeviceDTO> systemDevices) {
    this.systemDevices = systemDevices;
    return this;
  }

  public SystemUnitDTO addSystemDevicesItem(SystemDeviceDTO systemDevicesItem) {
    if (this.systemDevices == null) {
      this.systemDevices = new ArrayList<SystemDeviceDTO>();
    }
    this.systemDevices.add(systemDevicesItem);
    return this;
  }

  /**
  * Get systemDevices
  * @return systemDevices
  **/
  @Schema(description = "")
  public List<SystemDeviceDTO> getSystemDevices() {
    return systemDevices;
  }
  public void setSystemDevices(List<SystemDeviceDTO> systemDevices) {
    this.systemDevices = systemDevices;
  }
  public SystemUnitDTO users(List<UserDTO> users) {
    this.users = users;
    return this;
  }

  public SystemUnitDTO addUsersItem(UserDTO usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<UserDTO>();
    }
    this.users.add(usersItem);
    return this;
  }

  /**
  * Get users
  * @return users
  **/
  @Schema(description = "")
  public List<UserDTO> getUsers() {
    return users;
  }
  public void setUsers(List<UserDTO> users) {
    this.users = users;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemUnitDTO systemUnitDTO = (SystemUnitDTO) o;
    return Objects.equals(this.description, systemUnitDTO.description) &&
        Objects.equals(this.id, systemUnitDTO.id) &&
        Objects.equals(this.name, systemUnitDTO.name) &&
        Objects.equals(this.systemDevices, systemUnitDTO.systemDevices) &&
        Objects.equals(this.users, systemUnitDTO.users);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(description, id, name, systemDevices, users);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemUnitDTO {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    systemDevices: ").append(toIndentedString(systemDevices)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
