/*
 * WPCEM API
 * WPCEM API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SystemDeviceDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemDeviceResourceApi
 */
@Ignore
public class SystemDeviceResourceApiTest {

    private final SystemDeviceResourceApi api = new SystemDeviceResourceApi();

    /**
     * createSystemDevice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSystemDeviceUsingPOSTTest() throws ApiException {
        SystemDeviceDTO body = null;
        SystemDeviceDTO response = api.createSystemDeviceUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteSystemDevice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSystemDeviceUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteSystemDeviceUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllSystemDevices
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSystemDevicesUsingGETTest() throws ApiException {
        Boolean eagerload = null;
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<SystemDeviceDTO> response = api.getAllSystemDevicesUsingGET(eagerload, page, size, sort);

        // TODO: test validations
    }
    /**
     * getSystemDevice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSystemDeviceUsingGETTest() throws ApiException {
        Long id = null;
        SystemDeviceDTO response = api.getSystemDeviceUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateSystemDevice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSystemDeviceUsingPUTTest() throws ApiException {
        SystemDeviceDTO body = null;
        SystemDeviceDTO response = api.updateSystemDeviceUsingPUT(body);

        // TODO: test validations
    }
}
