/*
 * WPCEM API
 * WPCEM API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SystemUnitDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemUnitResourceApi
 */
@Ignore
public class SystemUnitResourceApiTest {

    private final SystemUnitResourceApi api = new SystemUnitResourceApi();

    /**
     * createSystemUnit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSystemUnitUsingPOSTTest() throws ApiException {
        SystemUnitDTO body = null;
        SystemUnitDTO response = api.createSystemUnitUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteSystemUnit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSystemUnitUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteSystemUnitUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllSystemUnits
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSystemUnitsUsingGETTest() throws ApiException {
        Boolean eagerload = null;
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<SystemUnitDTO> response = api.getAllSystemUnitsUsingGET(eagerload, page, size, sort);

        // TODO: test validations
    }
    /**
     * getSystemUnit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSystemUnitUsingGETTest() throws ApiException {
        Long id = null;
        SystemUnitDTO response = api.getSystemUnitUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateSystemUnit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSystemUnitUsingPUTTest() throws ApiException {
        SystemUnitDTO body = null;
        SystemUnitDTO response = api.updateSystemUnitUsingPUT(body);

        // TODO: test validations
    }
}
