/*
 * WPCEM API
 * WPCEM API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SystemDeviceTypeDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemDeviceTypeResourceApi
 */
@Ignore
public class SystemDeviceTypeResourceApiTest {

    private final SystemDeviceTypeResourceApi api = new SystemDeviceTypeResourceApi();

    /**
     * createSystemDeviceType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSystemDeviceTypeUsingPOSTTest() throws ApiException {
        SystemDeviceTypeDTO body = null;
        SystemDeviceTypeDTO response = api.createSystemDeviceTypeUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteSystemDeviceType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSystemDeviceTypeUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteSystemDeviceTypeUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * getAllSystemDeviceTypes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSystemDeviceTypesUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<SystemDeviceTypeDTO> response = api.getAllSystemDeviceTypesUsingGET(page, size, sort);

        // TODO: test validations
    }
    /**
     * getSystemDeviceType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSystemDeviceTypeUsingGETTest() throws ApiException {
        Long id = null;
        SystemDeviceTypeDTO response = api.getSystemDeviceTypeUsingGET(id);

        // TODO: test validations
    }
    /**
     * updateSystemDeviceType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSystemDeviceTypeUsingPUTTest() throws ApiException {
        SystemDeviceTypeDTO body = null;
        SystemDeviceTypeDTO response = api.updateSystemDeviceTypeUsingPUT(body);

        // TODO: test validations
    }
}
